### ISSUE TITLE
Less reloading of replays

### ISSUE THREAD

**Issue by nrabins** [ballparts/TagProReplays#12]
I think there's a lot of unnecessary reloading of replays that makes managing large replay collections difficult.

Some things that I think don't require a complete dataset reload: renaming, deleting from the list. It seems like you could simulate this in the UI instead of reloading and matching UI to the backing data.

I wonder if you could also keep the list up in the background behind the replay viewer so that when you exited you didn't need to reload there.

I don't know how feasible this all is, but it would help A LOT with managing collections.

**Comment by ballparts** [comment]
Okay, I'm releasing version 1.1.10 right now, and it *should* do what you're suggesting here. Let me know if there are bugs.

**Comment by nrabins** [comment]
Will do. I haven't run into any in my limited testing, and it's working
smoothly/quickly. Thanks!
