### ISSUE TITLE
[Serious Suggestion] Reddit integration

### ISSUE THREAD

**Issue by nrabins** [ballparts/TagProReplays#35]
Couple of ideas to make posting to Reddit a little easier.

1. Do away with downloading of videos. All that does is confuse people by allowing them to edit their replays into a cohesive and artistic montage or altering their clips in some way that highlights an interesting play.
2. Require users to enter their Reddit login information in order to save a clip.
3. Use aforementioned Reddit login information to automatically post a replay to the /r/tagpro subreddit whenever a replay is taken.
4. Don't allow users to disable this option.
5. Automatically choose a title for the post from among "rekt", "#planned", "past 4! oh...", and "developers pls".
6. If a user records a replay, all other users' extensions upvote the generated Reddit post as well as make comments such as "rekt", "you scrub", "lol", "hey i was in that game with you!".

I think this would save everyone a lot of time by cutting out the various middlemen between taking a replay of a mundane TagPro occurrence and posting a highlight of said occurrence on the sub.

**Comment by ballparts** [comment]
lol
