### ISSUE TITLE
Add a button that combines Crop, Rename, and Replace.

### ISSUE THREAD

**Issue by nrabins** [ballparts/TagProReplays#7]
This is my most used workflow, and right now it takes two steps (Crop and Replace -> Rename), which requires a reload of the replays list between them (~5 seconds). A single button that pops up a rename dialog and then does the crop, replace, and rename would be incredibly useful.

**Comment by ballparts** [comment]
This is an interesting idea. I might make it so that any time you crop or crop+replace, there is a pop up that gives you the opportunity to also rename.

**Comment by ballparts** [comment]
I did the idea I was thinking of doing, where you have the option to rename every time you crop or crop+replace. How is that working for you?

**Comment by nrabins** [comment]
It's working well! I like the implementation for my workflow.
